openapi: 3.0.3
info:
  title: The SpatioTemporal Asset Catalog API - Context Extension
  description: Adds search related metadata (context) to responses.
  version: 1.0.0-rc.1
  contact:
    name: STAC Specification
    url: 'http://stacspec.org'
  license:
    name: Apache License 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
paths: {}
components:
  schemas:
    itemCollection:
      type: object
      description: |-
        **Extension:** Context

        Augments lists of resources with the number of returned and matches resource and the given limit for the request.
      x-stac-api-fragment: context
      properties:
        'context':
          type: object
          required:
            - returned
          properties:
            returned:
              type: integer
              minimum: 0
              example: 1
            limit:
              type: integer
              nullable: true
              minimum: 0
              example: 5
            matched:
              type: integer
              minimum: 0
              example: 314159
